### PR TITLE
up2date and fixed

### PR DESCRIPTION
**Pull request by supernoodled**
updated the cheat to the latest update.

"fixed" the crash on loading ingame on team selection screen.
Misc FrameStageNotify is the problem, so "fixed" it by commenting it out.

edit: The only thing broken by the "fix" is the third person view.
ESP/glow is also broken but probably because something there needs updating.

### CODE REVIEW

**Comment by SamuelTulach** [comment]
@akasarx I have tried your fork and it actually works, just visuals are not working for some reason...

**Comment by akasarx** [comment]
Newest commit adds sanity checks to the saving, so for example saving or loading will no longer crash CSGO.

It also removes the IsDormant check as this no longer exists AFAIK

**Comment by akasarx** [comment]
Fixed cursor.
cl_mouseenable is no longer in the game, so replaced with InputSystem()->EnableInput();

**Comment by akasarx** [comment]
Added the full CInput struct, still can't fix the third person but oh well at least the cheat "works".
Interfaces::Input()->m_fCameraInThirdPerson on CMisc::FrameStageNotify is broken if anyone wants to try.

Also removed some client text as it's not needed anymore really.

**Comment by Yell0** [comment]
i can't some how get chames working

**Comment by xmodusEU** [comment]
**if you want a fix for esp/visuals/glow/chams contact me in discord: XMODUS#7784**

**Comment by soarvor** [comment]
how the hell do i find and update offsets in this shit cheat

**Pull request merged**
