### PR TITLE
updated hook (some things dont work like medal/chams other things too)

### PR DESCRIPTION
**Pull request by M1XT3NZ**
Yeah some things dont work because they need a little rewrite but im too lazy so hf

//edit 
also chams dont work but aim and esp works didnt really test anything else

### CODE REVIEW

**Comment by smefcc** [comment]
Will add a link to this on the main page. Until every feature is supported (or most popular ones, like chams etc) this will not be pulled

**Comment by thyanie** [comment]
Pull request rejected.

**Comment by akasarx** [comment]
Hook_Reset is broken in this, which causes crash when lost focus of window, to fix just replace it with this

```
HRESULT WINAPI Hook_Reset(LPDIRECT3DDEVICE9 pDevice, D3DPRESENT_PARAMETERS* pPresentationParameters)
		{
			Client::OnLostDevice();

			Client::OnResetDevice();

			return Reset_o(pDevice, pPresentationParameters);
		}
```

and then under the function Initialize, specifically underneath this line
device.hook_index(D3D9::TABLE::Reset, Hook_Reset);

add the line 
Reset_o = (Reset_t)device.get_original<ResetHook>(D3D9::TABLE::Reset);

**Comment by OscarRexid** [comment]
@akasarx i did exactly as you said but got 3 errors from it, any idea why?

Error 1: Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0304	no instance of function template "vfunc_hook::get_original" matches the argument list	smef_indigo	c:\Users\username\Desktop\smefs-Indigo-Remastered-master\INDIGO\Engine\Hook.cpp	147	

ERROR 2: Severity	Code	Description	Project	File	Line	Suppression State
Error	C2672	'vfunc_hook::get_original': no matching overloaded function found	smef_indigo	c:\users\username\desktop\smefs-indigo-remastered-master\indigo\engine\hook.cpp	147	

ERROR 3: Severity	Code	Description	Project	File	Line	Suppression State
Error	C2783	'T vfunc_hook::get_original(int)': could not deduce template argument for 'T'	smef_indigo	c:\users\swezl\desktop\smefs-indigo-remastered-master\indigo\engine\hook.cpp	147

**Comment by itsdezi** [comment]
Please fix these lines 79-88 in Skin.h

`extern WeaponSkins_s WeaponSkins[33];
extern KnifeSkins_s KnifeSkins[10];
extern Gloves_s GloveSkin[10];
extern unordered_map<int, EconomyItemCfg> g_SkinChangerCfg;
extern unordered_map<int, const char*> g_ViewModelCfg;
extern unordered_map<const char*, const char*> g_KillIconCfg;

extern char* pWeaponData[33];
extern int pWeaponItemIndexData[33];
extern char* pKnifeData[10];`

**Pull request closed without merging**
